version: '3'
services:
  web:
    build: apache
    ports:
    - 8000:80
    volumes:
      - ./apache/test.lan.conf:/etc/apache2/sites-enabled/test.lan.conf
      - ./apache/apache2.conf:/etc/apache2/apache2.conf
      - ./html:/web/test.lan
  dnsserver:
    build: dns
    command: ['--addn-hosts=/rexistros.txt']
    volumes:
      - ./dns/rexistros.txt:/rexistros.txt
  cliente:
    build: cliente
    volumes:
      - ./cliente/inicio.sh:/inicio.sh
    command: bash /inicio.sh
